### ISSUE TITLE
Errors in foaf.rdf

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/php-solid-server#10]
Looking at https://localhost/profile/card (while running the `dev` branch), I see:
```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns0: <http://webns.net/mvcb/> .

_:#me
  a foaf:Person ;
  foaf:depiction <https://www.gravatar.com/avatar/f8d7c4a4899736c59ec1e40c7021d477?s=1024> ;
  foaf:family_name "Peachey" ;
  foaf:givenname "Ben" ;
  foaf:homepage <https://pother.ca> ;
[...]
```

The test suite uses rdflib which uses N3Lexer and chokes on that `_:#me`:
```sh
 Unexpected "_:#me" on line 5.

      at N3Lexer._syntaxError (node_modules/n3/lib/N3Lexer.js:461:15)
      at reportSyntaxError (node_modules/n3/lib/N3Lexer.js:389:21)
      at N3Lexer._tokenizeToEnd (node_modules/n3/lib/N3Lexer.js:370:86)
      at node_modules/n3/lib/N3Lexer.js:480:83
```

I see the code refers to `/foaf.rdf` but I can only find that in https://github.com/pdsinterop/php-solid-server/blob/master/tests/fixtures/foaf.rdf which is different from the one that's being served at https://localhost/profile/card.

@potherca Is this using flysystem-rdf somehow?

**Comment by michielbdejong** [comment]
I think I have an idea of what may have happened here. Maybe you converted from rdf+xml to text/turtle, but didn't set a base url for the conversion? So instead of `<#me>` (relative to the current doc) it produced `_:#me` (relative to a blank node)

**Comment by Potherca** [comment]
Regarding your second comment, it is quite possible that the base URL is not set :disappointed: 

What happens on the road to `/profile/card` is:

1. The `tests/fixtures` directory is loaded as filesystem root in [`web/index.php#L43`](https://github.com/pdsinterop/php-solid-server/blob/master/web/index.php#L43)
2. `pdsinterop/flysystem-rdf` is loaded onto the filesystem in [`web/index.php#L46`](https://github.com/pdsinterop/php-solid-server/blob/master/web/index.php#L46)
3. The logic in `src/Controller/Profile/CardController.php` is invoked
4. The `/foaf.rdf` file is loaded (hard-coded value) from the filesystem in [`src/Controller/Profile/CardController.php#L31`](https://github.com/pdsinterop/php-solid-server/blob/master/src/Controller/Profile/CardController.php#L31)
5. The file content is read/converted to the request format in [`src/Controller/Profile/CardController.php#L51`](https://github.com/pdsinterop/php-solid-server/blob/master/src/Controller/Profile/CardController.php#L51)
6. The file content is returned.

If the conversion is causing too much trouble, the easiest fix would be to create a `card.ttl` dthat the test-suite does understand and use that for now, instead of the `.foaf. That should keep things moving for now, any issues with conversion could then be resolved downstream in `pdsinterop/flysystem-rdf` later.

**Comment by michielbdejong** [comment]
Right, it seems the empty node comes from https://github.com/pdsinterop/flysystem-rdf/blob/master/src/Flysystem/Plugin/ReadRdf.php#L64
That should be a named node for the URL of the doc (a relative url like '.' is probably ok)
