### ISSUE TITLE
/.well-known/openid-configuration broken in master?

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/php-solid-server#24]
Seeing this when running the solid-crud tests against latest master:
```sh
curl -ki https://server/.well-known/openid-configuration
HTTP/1.1 200 OK
Date: Thu, 05 Nov 2020 15:53:11 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.2.34
Set-Cookie: PHPSESSID=aa38720335c40966e6bae7a66f382ac7; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Length: 1534
Content-Type: text/html; charset=UTF-8

<br />
<b>Warning</b>:  file_put_contents(/app/src/Controller/../../config/serverConfig.json): failed to open stream: Permission denied in <b>/app/src/ServerConfig.php</b> on line <b>30</b><br />
<br />
<b>Warning</b>:  file_get_contents(/app/src/Controller/../../config/serverConfig.json): failed to open stream: No such file or directory in <b>/app/src/ServerConfig.php</b> on line <b>27</b><br />
<br />
<b>Fatal error</b>:  Uncaught TypeError: json_decode() expects parameter 1 to be string, boolean given in /app/src/ServerConfig.php:27
Stack trace:
#0 /app/src/ServerConfig.php(27): json_decode(false, true)
#1 /app/src/ServerConfig.php(14): Pdsinterop\Solid\ServerConfig-&gt;loadConfig()
#2 /app/src/Controller/ServerController.php(18): Pdsinterop\Solid\ServerConfig-&gt;__construct('/app/src/Contro...')
#3 [internal function]: Pdsinterop\Solid\Controller\ServerController-&gt;__construct()
#4 /app/vendor/league/container/src/Definition/Definition.php(252): ReflectionClass-&gt;newInstanceArgs(Array)
#5 /app/vendor/league/container/src/Definition/Definition.php(212): League\Container\Definition\Definition-&gt;resolveClass('Pdsinterop\\Soli...')
#6 /app/vendor/league/container/src/Definition/DefinitionAggregate.php(94): League\Container\Definition\Definition-&gt;resolve(false)
#7 /app/vendor/league/container/src/Container.php(157): League\Container\Definition\DefinitionAggregate-&gt;resolve('Pdsinterop\\Soli...', false)
#8 /app/vendor/league/route/src/Rout in <b>/app/src/ServerConfig.php</b> on line <b>27</b><br />

**Comment by michielbdejong** [comment]
Probably due to https://github.com/pdsinterop/php-solid-server/pull/20/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R24

**Comment by michielbdejong** [comment]
Seems to be fixed now
